[build]
command = "ng build && ng run {projectName}:serverless:production"
publish = "dist/{projectName}/browser"
functions = "netlify/functions"

[[plugins]]
package = "@netlify/plugin-angular-universal"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run start"
  functions = "netlify/functions"

